### ISSUE TITLE
Environment Dev doesn't work

### ISSUE THREAD

**Issue by leduong** [openfun/openedx-docker#293]
## Environment Dev doesn't work with ironwood.2

```
.:: OPENEDX-DOCKER ::.

== Active configuration ==
$ make info
* EDX_RELEASE                : ironwood.2
* FLAVOR                     : oee
* FLAVORED_EDX_RELEASE_PATH  : build
* EDX_RELEASE_REF            : open-release/ironwood.2
* EDX_ARCHIVE_URL            : https://github.com/edx/edx-platform/archive/open-release/ironwood.2.tar.gz
* EDX_DEMO_RELEASE_REF       : open-release/ironwood.2
* EDX_DEMO_ARCHIVE_URL       : https://github.com/edx/edx-demo-course/archive/open-release/ironwood.2.tar.gz
* REDIS_SERVICE              : redis
* EDXAPP_IMAGE_NAME          : edxapp
* EDXAPP_IMAGE_TAG           : ironwood.2-oee
* EDXAPP_NGINX_IMAGE_NAME    : edxapp-nginx
```

## Actual Behavior
```
$ make dev
or
$ ./bin/compose up lms-dev
```

## Steps to Reproduce

```
make dev
DOCKER_UID=1000 DOCKER_GID=1000 FLAVORED_EDX_RELEASE_PATH="releases/ironwood/2/oee" EDXAPP_IMAGE_TAG=ironwood.2-oee docker-compose run --rm -e HOME="/tmp" --no-deps lms-dev bash -c "\
  rm -f /edx/app/edxapp/edx-platform/lms/envs/fun && \
  rm -f /edx/app/edxapp/edx-platform/cms/envs/fun && \
  ln -sf /config/lms /edx/app/edxapp/edx-platform/lms/envs/fun && \
  ln -sf /config/cms /edx/app/edxapp/edx-platform/cms/envs/fun && \
  ln -sf /config/lms/root_urls.py /edx/app/edxapp/edx-platform/lms/ && \
  ln -sf /config/cms/root_urls.py /edx/app/edxapp/edx-platform/cms/"
Creating openedx-docker_lms-dev_run ... done
# starts lms-dev as well via docker-compose dependency
DOCKER_UID=1000 DOCKER_GID=1000 FLAVORED_EDX_RELEASE_PATH="releases/ironwood/2/oee" EDXAPP_IMAGE_TAG=ironwood.2-oee docker-compose up -d cms-dev
openedx-docker_mongodb_1 is up-to-date
openedx-docker_mailcatcher_1 is up-to-date
openedx-docker_redis_1 is up-to-date
openedx-docker_memcached_1 is up-to-date
openedx-docker_mysql_1 is up-to-date
Creating openedx-docker_lms-dev_1 ... done
Creating openedx-docker_cms-dev_1 ... done
Wait for services to be up...
DOCKER_UID=1000 DOCKER_GID=1000 FLAVORED_EDX_RELEASE_PATH="releases/ironwood/2/oee" EDXAPP_IMAGE_TAG=ironwood.2-oee docker-compose run --rm -e HOME="/tmp" dockerize -wait tcp://mysql:3306 -timeout 60s
Creating openedx-docker_dockerize_run ... done
2021/07/06 05:37:01 Waiting for: tcp://mysql:3306
2021/07/06 05:37:01 Connected to tcp://mysql:3306
DOCKER_UID=1000 DOCKER_GID=1000 FLAVORED_EDX_RELEASE_PATH="releases/ironwood/2/oee" EDXAPP_IMAGE_TAG=ironwood.2-oee docker-compose run --rm -e HOME="/tmp" dockerize -wait tcp://cms-dev:8000 -timeout 60s
Creating openedx-docker_dockerize_run ... done
2021/07/06 05:37:02 Waiting for: tcp://cms-dev:8000
2021/07/06 05:37:02 Problem with dial: dial tcp 172.20.0.11:8000: getsockopt: connection refused. Sleeping 1s
2021/07/06 05:37:03 Problem with dial: dial tcp 172.20.0.11:8000: getsockopt: connection refused. Sleeping 1s
2021/07/06 05:37:04 Problem with dial: dial tcp 172.20.0.11:8000: getsockopt: connection refused. Sleeping 1s
```
OR
```
./bin/compose up lms-dev
openedx-docker_mailcatcher_1 is up-to-date
openedx-docker_mongodb_1 is up-to-date
openedx-docker_mysql_1 is up-to-date
openedx-docker_memcached_1 is up-to-date
openedx-docker_redis_1 is up-to-date
Starting openedx-docker_lms-dev_1 ... done
Attaching to openedx-docker_lms-dev_1
lms-dev_1         | WARNING:py.warnings:/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
lms-dev_1         |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
lms-dev_1         | 
lms-dev_1         | Traceback (most recent call last):
lms-dev_1         |   File "manage.py", line 120, in <module>
lms-dev_1         |     startup.run()
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/lms/startup.py", line 19, in run
lms-dev_1         |     django.setup()
lms-dev_1         |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
lms-dev_1         |     apps.populate(settings.INSTALLED_APPS)
lms-dev_1         |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
lms-dev_1         |     app_config.import_models()
lms-dev_1         |   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
lms-dev_1         |     self.models_module = import_module(models_module_name)
lms-dev_1         |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
lms-dev_1         |     __import__(name)
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/bulk_email/models.py", line 16, in <module>
lms-dev_1         |     from openedx.core.djangoapps.course_groups.cohorts import get_cohort_by_name
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/course_groups/cohorts.py", line 9, in <module>
lms-dev_1         |     from courseware import courses
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/courses.py", line 25, in <module>
lms-dev_1         |     from courseware.module_render import get_module
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 60, in <module>
lms-dev_1         |     from openedx.core.djangoapps.bookmarks.services import BookmarksService
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/bookmarks/services.py", line 12, in <module>
lms-dev_1         |     from . import DEFAULT_FIELDS, api
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/bookmarks/api.py", line 11, in <module>
lms-dev_1         |     from .models import Bookmark
lms-dev_1         |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/bookmarks/models.py", line 41, in <module>
lms-dev_1         |     class Bookmark(TimeStampedModel):
lms-dev_1         |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 118, in __new__
lms-dev_1         |     "INSTALLED_APPS." % (module, name)
lms-dev_1         | RuntimeError: Model class openedx.core.djangoapps.bookmarks.models.Bookmark doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
openedx-docker_lms-dev_1 exited with code 1
```

## Specifications

- Version: master
- Platform: ubuntu 20.04

**Comment by jmaupetit** [comment]
Did you run `make bootstrap` before running `make dev`?

**Comment by leduong** [comment]
@jmaupetit It's worked with `make bootstrap`
